// <auto-generated />
using System;
using CakeWebApp_DotNetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CakeWebApp_DotNetCore.Migrations
{
    [DbContext(typeof(ProjectDBContext))]
    [Migration("20190525151005_InitialCreare")]
    partial class InitialCreare
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.CHITIETGIOHANG", b =>
                {
                    b.Property<int>("MaGioHang");

                    b.Property<int>("MaSanPham");

                    b.Property<int>("SoLuongSP");

                    b.Property<string>("ThanhTien")
                        .HasMaxLength(12);

                    b.HasKey("MaGioHang", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHITIETGIOHANGs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.CHUCVU", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("MaChucVu");

                    b.ToTable("CHUCVUs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.DANHMUCSANPHAM", b =>
                {
                    b.Property<int>("MaDanhMuc");

                    b.Property<int?>("MaDanhMucCha");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DANHMUCSANPHAMs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.DONHANG", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaGiaoDich");

                    b.Property<int?>("MaNhanVien");

                    b.Property<string>("TinhTrangGiaohang")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaGiaoDich");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DONHANGs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.GIAODICH", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200);

                    b.Property<int>("MaGioHang");

                    b.Property<int?>("MaKhachHang");

                    b.Property<int?>("MaThanhVien");

                    b.Property<DateTime>("ThoiDiemGiaoDich");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("TongTien")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaThanhVien");

                    b.ToTable("GIAODICHes");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.GIOHANG", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SoLuongLoaiSP");

                    b.Property<string>("TongTien")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("MaGioHang");

                    b.ToTable("GIOHANGs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.HINHANH", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("MaHinhAnh");

                    b.ToTable("HINHANHs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.KHACHHANG", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("TenKhachhang")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaKhachHang");

                    b.ToTable("KHACHHANGs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.LOAIADMIN", b =>
                {
                    b.Property<int>("MaLoaiAdmin")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiAdmin")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("MaLoaiAdmin");

                    b.ToTable("LOAIADMINs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.NHANVIEN", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("MaChucVu");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("TienLuong")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("TienTroCap")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NHANVIENs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.SANPHAM", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChietKhau")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("GiaBan")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<int>("LuotThichSP");

                    b.Property<int>("LuotXemSP");

                    b.Property<int>("MaDanhMuc");

                    b.Property<int>("MaHinhAnh");

                    b.Property<DateTime>("NgayTaoSP")
                        .HasColumnType("date");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaHinhAnh");

                    b.ToTable("SANPHAMs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.TAIKHOANADMIN", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaLoaiAdmin");

                    b.Property<int?>("MaNhanVien");

                    b.Property<string>("PasswordTK")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaLoaiAdmin");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("TAIKHOANADMINs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.THANHVIEN", b =>
                {
                    b.Property<int>("MaThanhVien")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("PasswordTK")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("TenThanhVien")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("MaThanhVien");

                    b.ToTable("THANHVIENs");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.CHITIETGIOHANG", b =>
                {
                    b.HasOne("CakeWebApp_DotNetCore.Models.GIOHANG", "GIOHANG")
                        .WithMany("CHITIETGIOHANG")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CakeWebApp_DotNetCore.Models.SANPHAM", "SANPHAM")
                        .WithMany("CHITIETGIOHANG")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.DANHMUCSANPHAM", b =>
                {
                    b.HasOne("CakeWebApp_DotNetCore.Models.DANHMUCSANPHAM", "DANHMUCSANPHAM2")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.DONHANG", b =>
                {
                    b.HasOne("CakeWebApp_DotNetCore.Models.GIAODICH", "GIAODICH")
                        .WithMany()
                        .HasForeignKey("MaGiaoDich")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CakeWebApp_DotNetCore.Models.NHANVIEN", "NHANVIEN")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.GIAODICH", b =>
                {
                    b.HasOne("CakeWebApp_DotNetCore.Models.GIOHANG", "GIOHANG")
                        .WithMany()
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CakeWebApp_DotNetCore.Models.KHACHHANG", "KHACHHANG")
                        .WithMany()
                        .HasForeignKey("MaKhachHang");

                    b.HasOne("CakeWebApp_DotNetCore.Models.THANHVIEN", "THANHVIEN")
                        .WithMany()
                        .HasForeignKey("MaThanhVien");
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.NHANVIEN", b =>
                {
                    b.HasOne("CakeWebApp_DotNetCore.Models.CHUCVU", "CHUCVU")
                        .WithMany()
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.SANPHAM", b =>
                {
                    b.HasOne("CakeWebApp_DotNetCore.Models.DANHMUCSANPHAM", "DANHMUCSANPHAM")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CakeWebApp_DotNetCore.Models.HINHANH", "HINHANH")
                        .WithMany()
                        .HasForeignKey("MaHinhAnh")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CakeWebApp_DotNetCore.Models.TAIKHOANADMIN", b =>
                {
                    b.HasOne("CakeWebApp_DotNetCore.Models.LOAIADMIN", "LOAIADMIN")
                        .WithMany()
                        .HasForeignKey("MaLoaiAdmin")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CakeWebApp_DotNetCore.Models.NHANVIEN", "NHANVIEN")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
